backend:
  name: git-gateway
  branch: main

media_folder: src/media
public_folder: /media

publish_mode: editorial_workflow
site_url: https://blog.thelist.app
display_url: https://blog.thelist.app

collections:
  - name: posts
    label: Posts
    folder: src/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: markdown
      - label: Date
        name: date
        widget: date
        default: ""
      - label: Body
        name: body
        widget: markdown
      - label: Banner Image
        name: bannerImage
        widget: image
