backend:
  name: git-gateway
  branch: main

media_folder: src/media/uploads
public_folder: /media/uploads

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Date
        name: date
        widget: date
        default: ""
      - label: Body
        name: body
        widget: markdown
      - label: Banner Image
        name: bannerImage
        widget: image
